# Generated by Django 3.0.7 on 2024-10-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs_in_playlist',
            field=models.ManyToManyField(related_name='playlist_to_songs', to='main.playlist_song'),
        ),
    ]
