# Generated by Django 3.0.7 on 2024-10-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20241016_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='songs_in_playlist',
            new_name='songs',
        ),
    ]
